### ISSUE TITLE
 ImageWorks manifests are broken

### ISSUE THREAD

**Issue by eliotjordan** [pulibrary/plum#1202]
Manifests can't be built for ImageWorks. This is the error raised:

```
F, [2017-04-20T10:00:03.952613 #7136] FATAL -- : NoMethodError (undefined method `pdf_type' for #<ImageWorkShowPresenter:0x007f07af04d108>):
F, [2017-04-20T10:00:03.952765 #7136] FATAL -- :
F, [2017-04-20T10:00:03.952819 #7136] FATAL -- : app/services/manifest_builder/pdf_link_builder.rb:12:in `apply'
app/services/manifest_builder/composite_builder.rb:11:in `block in apply'
app/services/manifest_builder/composite_builder.rb:10:in `each'
app/services/manifest_builder/composite_builder.rb:10:in `apply'
app/services/manifest_builder.rb:9:in `initialize'
app/services/polymorphic_manifest_builder.rb:7:in `new'
app/services/polymorphic_manifest_builder.rb:7:in `new'
app/controllers/concerns/hyrax/manifest.rb:39:in `block in manifest_builder'
app/controllers/concerns/hyrax/manifest.rb:38:in `manifest_builder'
app/controllers/concerns/hyrax/manifest.rb:8:in `block (2 levels) in manifest'
app/controllers/concerns/hyrax/manifest.rb:6:in `manifest'
```

**Comment by escowles** [comment]
Probably this new line added to handle pdf_type of "none": https://github.com/pulibrary/plum/blob/master/app/services/manifest_builder/pdf_link_builder.rb#L12

**Comment by eliotjordan** [comment]
Yeah, just needed to add `pdf_type` to the show presenter.
