### ISSUE TITLE
Can't save MultiVolumeWorks containing ScannedResources

### ISSUE THREAD

**Issue by escowles** [pulibrary/plum#633]
It's getting a type mismatch in the CollectionIndexing module where it expects a FileSet and gets a ScannedResource

**Comment by tpendragon** [comment]
It's actually when trying to index the thumbnail:

```
ActiveFedora::ActiveFedoraError: Model mismatch. Expected FileSet. Got: ScannedResource
        from /opt/plum/shared/bundle/ruby/2.2.0/bundler/gems/active_fedora-29933f5ee036/lib/active_fedora/relation/finder_methods.rb:204:in `class_to_load'
        from /opt/plum/shared/bundle/ruby/2.2.0/bundler/gems/active_fedora-29933f5ee036/lib/active_fedora/relation/finder_methods.rb:195:in `load_from_fedora'
        from /opt/plum/shared/bundle/ruby/2.2.0/bundler/gems/active_fedora-29933f5ee036/lib/active_fedora/relation/finder_methods.rb:181:in `find_one'
        from /opt/plum/shared/bundle/ruby/2.2.0/bundler/gems/active_fedora-29933f5ee036/lib/active_fedora/relation/finder_methods.rb:228:in `find_with_ids'
        from /opt/plum/shared/bundle/ruby/2.2.0/bundler/gems/active_fedora-29933f5ee036/lib/active_fedora/relation/finder_methods.rb:52:in `find'
        from /opt/plum/shared/bundle/ruby/2.2.0/bundler/gems/active_fedora-29933f5ee036/lib/active_fedora/querying.rb:3:in `find'
        from /opt/plum/shared/bundle/ruby/2.2.0/bundler/gems/curation_concerns-f68c98d265d7/app/services/curation_concerns/thumbnail_path_service.rb:22:in `fetch_thumbnail'
        from /opt/plum/shared/bundle/ruby/2.2.0/bundler/gems/curation_concerns-f68c98d265d7/app/services/curation_concerns/thumbnail_path_service.rb:9:in `call'
        from /opt/plum/shared/bundle/ruby/2.2.0/bundler/gems/curation_concerns-f68c98d265d7/app/services/curation_concerns/indexes_thumbnails.rb:27:in `thumbnail_path'
        from /opt/plum/shared/bundle/ruby/2.2.0/bundler/gems/curation_concerns-f68c98d265d7/app/services/curation_concerns/indexes_thumbnails.rb:22:in `index_thumbnails'
        from /opt/plum/shared/bundle/ruby/2.2.0/bundler/gems/curation_concerns-f68c98d265d7/app/services/curation_concerns/indexes_thumbnails.rb:15:in `block in generate_solr_document'
        from /opt/plum/shared/bundle/ruby/2.2.0/bundler/gems/curation_concerns-f68c98d265d7/app/services/curation_concerns/indexes_thumbnails.rb:14:in `tap'
        from /opt/plum/shared/bundle/ruby/2.2.0/bundler/gems/curation_concerns-f68c98d265d7/app/services/curation_concerns/indexes_thumbnails.rb:14:in `generate_solr_document'
        from /opt/plum/shared/bundle/ruby/2.2.0/bundler/gems/curation_concerns-f68c98d265d7/app/indexers/curation_concerns/work_indexer.rb:5:in `generate_solr_document'
        from /opt/plum/shared/bundle/ruby/2.2.0/bundler/gems/active_fedora-29933f5ee036/lib/active_fedora/indexing.rb:33:in `to_solr'
        from /opt/plum/shared/bundle/ruby/2.2.0/bundler/gems/curation_concerns-f68c98d265d7/app/models/concerns/curation_concerns/human_readable_type.rb:11:in `to_solr'
        from /opt/plum/shared/bundle/ruby/2.2.0/gems/hydra-access-controls-10.0.0.beta4/app/models/concerns/hydra/access_controls/permissions.rb:29:in `to_solr'
        from /opt/plum/shared/bundle/ruby/2.2.0/gems/hydra-access-controls-10.0.0.beta4/app/models/concerns/hydra/access_controls/embargoable.rb:37:in `to_solr'
        from /opt/plum/releases/20160525144022/app/models/concerns/structural_metadata.rb:9:in `to_solr'
        from /opt/plum/releases/20160525144022/app/models/concerns/collection_indexing.rb:4:in `to_solr'
        from (irb):2
        from /opt/plum/shared/bundle/ruby/2.2.0/gems/railties-4.2.4/lib/rails/commands/console.rb:110:in `start'
        from /opt/plum/shared/bundle/ruby/2.2.0/gems/railties-4.2.4/lib/rails/commands/console.rb:9:in `start'
        from /opt/plum/shared/bundle/ruby/2.2.0/gems/railties-4.2.4/lib/rails/commands/commands_tasks.rb:68:in `console'
        from /opt/plum/shared/bundle/ruby/2.2.0/gems/railties-4.2.4/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
        from /opt/plum/shared/bundle/ruby/2.2.0/gems/railties-4.2.4/lib/rails/commands.rb:17:in `<top (required)>'
        from bin/rails:8:in `require'
```
